name: Deploy DemoDerby to sarcastichedgehog.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DemoDerby repo
        uses: actions/checkout@v4
        with:
          path: demoderby_game

      - name: Create config.js for DemoDerby
        working-directory: ./demoderby_game
        run: |
          echo "window.APP_CONFIG = {" > config.js
          echo "  API_KEY: \"${{ secrets.MULTISYNQ_API_KEY }}\"," >> config.js
          echo "  APP_ID: \"${{ secrets.MULTISYNQ_APP_ID }}\"" >> config.js
          echo "};" >> config.js
        shell: bash

      - name: Checkout sarcastichedgehog.com website repo
        uses: actions/checkout@v4
        with:
          repository: SarcyHedgehog/sarcastichedgehog.com
          path: website_repo
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

      - name: Copy DemoDerby files to website repo
        run: |
          TARGET_DIR="./website_repo/demoderby"
          mkdir -p "$TARGET_DIR"
          cp ./demoderby_game/index.html "$TARGET_DIR/index.html"
          cp ./demoderby_game/config.js "$TARGET_DIR/config.js"
        shell: bash

      - name: Commit and push changes to website repo
        env:
          GIT_USER_NAME: "GitHub Actions Bot"
          GIT_USER_EMAIL: "actions@github.com"
        run: |
          cd ./website_repo
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
          else
            git config user.name "${GIT_USER_NAME}"
            git config user.email "${GIT_USER_EMAIL}"
            git add .
            git commit -m "Deploy DemoDerby update"
            git push origin main
          fi
        shell: bash
